spring:
  application:
    name: eureka
    path: /eureka
    env: prod
  jackson:
    default-property-inclusion: non_null
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
eureka:
  instance:
    hostname: 172.17.0.1
    prefer-ip-address: false
    environment: prod
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    filter-only-up-instances: false
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000